// sauce, meats, veggies, drizzles

export default [
  [
    {
      photo: "Alfredo",
      key: {
        Alfredo: "Alfredo",
        "Traditional Red": "Traditionalred",
        "Zesty Red": "Zestyred",
        Pesto: "Pesto",
        "no-sauce": "Nosauce",
      },
    },
    {
      photo: "Traditionalred",
      key: {
        Alfredo: "Alfredo",
        "Traditional Red": "Traditionalred",
        "Zesty Red": "Zestyred",
        Pesto: "Pesto",
        "no-sauce": "Nosauce",
      },
    },
    {
      photo: "Zestyred",
      key: {
        Alfredo: "Alfredo",
        "Traditional Red": "Traditionalred",
        "Zesty Red": "Zestyred",
        Pesto: "Pesto",
        "no-sauce": "Nosauce",
      },
    },
    {
      photo: "Pesto",
      key: {
        Alfredo: "Alfredo",
        "Traditional Red": "Traditionalred",
        "Zesty Red": "Zestyred",
        Pesto: "Pesto",
        "no-sauce": "Nosauce",
      },
    },
    {
      photo: "Nosauce",
      key: {
        Alfredo: "Alfredo",
        "Traditional Red": "Traditionalred",
        "Zesty Red": "Zestyred",
        Pesto: "Pesto",
        "no-sauce": "Nosauce",
      },
    },
  ],
  [
    {
      photo: "Meatballs", // Change Later
      key: {
        "Italian Sausage": "Italiansasuage",
        "Diced Ham": "Dicedham",
        Salami: "Salami",
        Pepperoni: "Pepperoni",
        "Smoked Chicken": "Smokedchicken",
        Meatballs: "Meatballs",
      },
    },
    {
      photo: "Dicedham",
      key: {
        "Italian Sausage": "Italiansasuage",
        "Diced Ham": "Dicedham",
        Salami: "Salami",
        Pepperoni: "Pepperoni",
        "Smoked Chicken": "Smokedchicken",
        Meatballs: "Meatballs",
      },
    },
    {
      photo: "Italiansasuage",
      key: {
        "Italian Sausage": "Italiansasuage",
        "Diced Ham": "Dicedham",
        Salami: "Salami",
        Pepperoni: "Pepperoni",
        "Smoked Chicken": "Smokedchicken",
        Meatballs: "Meatballs",
      },
    },
    {
      photo: "Salami",
      key: {
        "Italian Sausage": "Italiansasuage",
        "Diced Ham": "Dicedham",
        Salami: "Salami",
        Pepperoni: "Pepperoni",
        "Smoked Chicken": "Smokedchicken",
        Meatballs: "Meatballs",
      },
    },
    {
      photo: "Pepperoni",
      key: {
        "Italian Sausage": "Italiansasuage",
        "Diced Ham": "Dicedham",
        Salami: "Salami",
        Pepperoni: "Pepperoni",
        "Smoked Chicken": "Smokedchicken",
        Meatballs: "Meatballs",
      },
    },
    {
      photo: "Smokedchicken",
      key: {
        "Italian Sausage": "Italiansasuage",
        "Diced Ham": "Dicedham",
        Salami: "Salami",
        Pepperoni: "Pepperoni",
        "Smoked Chicken": "Smokedchicken",
        Meatballs: "Meatballs",
      },
    },
  ],
  [
    {
      photo: "Mushrooms",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Greenpepper",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Olive",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Jalapenos",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Roastedgarlic",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Spinach",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Tomatoes",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Pineapple",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Onion",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
    {
      photo: "Bananapepper",
      key: {
        Mushrooms: "Mushrooms",
        "Green Peppers": "Greenpepper",
        "Black Olives": "Olive",
        Jalapenos: "Jalapenos",
        "Roasted Garlic": "Roastedgarlic",
        Spinach: "Spinach",
        Tomatoes: "Tomatoes",
        Pineapple: "Pineapple",
        Onions: "Onion",
        "Banana Peppers": "Bananapepper",
      },
    },
  ],
  [
    {
      photo: "Ranch",
      key: {
        Ranch: "Ranch",
        "BBQ Sauce": "Bbqsauce",
        Sriracha: "Siracha",
        "Olive Oil": "Oliveoil",
        Oregano: "Oregano",
      },
    },
    {
      photo: "Bbqsauce",
      key: {
        Ranch: "Ranch",
        "BBQ Sauce": "Bbqsauce",
        Siracha: "Siracha",
        "Olive Oil": "Oliveoil",
        Oregano: "Oregano",
      },
    },
    {
      photo: "Siracha",
      key: {
        Ranch: "Ranch",
        "BBQ Sauce": "Bbqsauce",
        Siracha: "Siracha",
        "Olive Oil": "Oliveoil",
        Oregano: "Oregano",
      },
    },
    {
      photo: "Oliveoil",
      key: {
        Ranch: "Ranch",
        "BBQ Sauce": "Bbqsauce",
        Siracha: "Siracha",
        "Olive Oil": "Oliveoil",
        Oregano: "Oregano",
      },
    },
    {
      photo: "Oregano",
      key: {
        Ranch: "Ranch",
        "BBQ Sauce": "Bbqsauce",
        Siracha: "Siracha",
        "Olive Oil": "Oliveoil",
        Oregano: "Oregano",
      },
    },
  ],
];
